Add .pep8speaks.yml
privacyidea/privacyidea pull request #1972
Opened 2019-12-19 14:21 UTC by NuvandaPV

2019-12-19 14:22 UTC, NuvandaPV commented
fixes #1959

2019-12-19 15:49 UTC, cornelinux requested changes

2019-12-19 15:49 UTC, cornelinux commented on .pep8speaks.yml
> +        - E711 # Comparison to None should be `if cond is None:`.
please remove this

2019-12-19 15:49 UTC, cornelinux commented on .pep8speaks.yml
> +        - E712 # Comparison to True should be `if cond is True:` or `if cond:`.
remove this

2019-12-19 15:49 UTC, cornelinux commented on .pep8speaks.yml
> +        - E241 # Multiple spaces after `,`.
this is cool. please remove this

2019-12-19 15:49 UTC, cornelinux commented on .pep8speaks.yml
> +        - E226 # Missing whitespace around arithmetic operator,
remove this

2019-12-19 15:49 UTC, cornelinux commented on .pep8speaks.yml
> +        - E133 # Closing bracket is missing indentation.
change this to E123

2019-12-19 15:49 UTC, cornelinux commented on .pep8speaks.yml
> +    hang-closing: False
Set to "True"

2019-12-20 09:15 UTC, cornelinux approved these changes

2019-12-20 09:15 UTC, merged