Add documentation about RADIUS configuration
privacyidea/privacyidea pull request #2449
Opened 2020-10-15 11:05 UTC by cornelinux

This is to avoid the misunderstanding, that
the admin could configure a RADIUS server
that would receive a request.

Closes #2448

2020-10-20 10:25 UTC, plettich requested changes
looks good, please fix typo

2020-10-20 10:25 UTC, plettich commented on doc/configuration/radiusserver_config.rst
> +.. note:: This is ment for outgoing RADIUS requests, not for incoming RADIUS requests!
please fix this typo

2020-10-20 10:36 UTC, cornelinux commented on doc/configuration/radiusserver_config.rst
> +.. note:: This is ment for outgoing RADIUS requests, not for incoming RADIUS requests!
done in 4a2c90b3

2020-10-23 14:28 UTC, plettich approved these changes
Looks good

2020-10-23 14:29 UTC, merged