Differentiate in C/R between tokens with/out DB-challenge
privacyidea/privacyidea pull request #2497
Opened 2020-11-05 13:25 UTC by cornelinux

A response to a challenge can arrive so late, that the
original challenge does not exist anymore in the database.
It still would be a response to a challenge, so we need to
differentiate between being a legit or non-legit response at all
(it has a "transaction_id")
and a response, for which still a challenge-DB-object exists.

When merging this PR, it will also rendet this PR useless:
Closes #2493

After all it...
Closes #2491

2020-11-05 13:26 UTC, cornelinux commented
This is another approach than #2493. I like this here more, since it is clearer about categorizing the tokens in the ``token_lists`` in ``lib/token.py:check_token_list``.

2020-11-10 14:50 UTC, plettich requested changes
just a minor typo

2020-11-10 14:50 UTC, plettich commented on privacyidea/lib/tokenclass.py
> +        This method checks, if this is a request  that is supposed to be
please remove superfluous space

2020-11-10 14:52 UTC, cornelinux commented on privacyidea/lib/tokenclass.py
> +        This method checks, if this is a request  that is supposed to be
Hawk eye. Did not see that! Will do!

2020-11-10 15:28 UTC, plettich approved these changes
looks good

2020-11-11 13:02 UTC, merged