2594/fix import of yubicos pskc
privacyidea/privacyidea pull request #2607
Opened 2021-01-29 12:34 UTC by timosturm

Closes #2594. Supports importing keys, where the algorithm matches `http://www.yubico.com/#yubikey-aes` or `urn:ietf:params:xml:ns:keyprov:pskc:hotp`.

The second identifier is the same for non yubikey tokens, therefor we check if the tokens key matches the pattern `<SerialNo>:<Slot>`also.

2021-02-03 08:01 UTC, laclaro requested changes
Please change the serial mapping slightly to UBAM (yubikey) and UBOM (hotp)

2021-02-04 09:26 UTC, timosturm commented on privacyidea/lib/importotp.py
> +
Why do you suggest changing `serial` to `**serial`?

2021-02-04 10:21 UTC, laclaro commented on privacyidea/lib/importotp.py
> +
Just a typo ;)

2021-02-04 10:22 UTC, laclaro approved these changes
Thank's

2021-02-04 10:23 UTC, merged