2677/tags in sms
privacyidea/privacyidea pull request #2684
Opened 2021-03-25 19:50 UTC by cornelinux

2021-03-25 19:50 UTC, pep8speaks commented
Hello @cornelinux! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`privacyidea/lib/tokens/smstoken.py`](https://github.com/privacyidea/privacyidea/blob/edc31a02932afb837334058b36b065ee2d3d16df/privacyidea/lib/tokens/smstoken.py):

> [Line 56:43](https://github.com/privacyidea/privacyidea/blob/edc31a02932afb837334058b36b065ee2d3d16df/privacyidea/lib/tokens/smstoken.py#L56): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','

2021-03-26 14:56 UTC, plettich reviewed
Looks good, just a short comment

2021-03-26 15:19 UTC, cornelinux commented on doc/policies/authentication.rst
> +
haha. I also thought about that email allows to add a `file:/...` to contain the template. But well, due to the SHORT message system this did not seem sensible to me :-)

I think the hint that the gateway might fail with too long messages is a good idea!

2021-03-26 15:26 UTC, cornelinux commented on doc/policies/authentication.rst
> +
done in d37bef44

2021-03-30 09:45 UTC, plettich requested changes
Looks good, just a minor spelling issue

2021-03-30 09:45 UTC, plettich commented on doc/policies/authentication.rst
> +   reject to long messages or the delivery could fail.
... reject *too* long ...

2021-03-30 10:06 UTC, cornelinux commented on doc/policies/authentication.rst
> +   reject to long messages or the delivery could fail.
Done in 40e2f5f3

2021-03-30 10:07 UTC, plettich approved these changes
Looks good

2021-03-30 10:29 UTC, merged