Token rollover
privacyidea/privacyidea pull request #2741
Opened 2021-05-25 12:47 UTC by cornelinux

This is an alternative implementation of the token rollover.
It uses the normal insite token enrollment and also
allows to change data (key length, otp length) if the administrator
allows so.

Still missing the webui policy.

Working on #2613

2021-05-25 12:48 UTC, cornelinux commented
@laclaro I would like to discuss this.

2021-06-01 13:31 UTC, laclaro requested changes
Please remove the hints to a button in the token list as we do not implement it with this PR.

2021-06-01 13:31 UTC, laclaro commented on doc/policies/webui.rst
> +displayed in the token details and in the token list. This button will generate a
this PR leaves the token list untouched.

2021-06-01 13:31 UTC, laclaro commented on privacyidea/lib/policy.py
> +                          'details and in the token list.'),
see above. Please remove token list.

2021-06-01 13:34 UTC, laclaro approved these changes
I quickly corrected the descriptions.

2021-06-01 13:34 UTC, merged