Catch error in last_auth_newer
privacyidea/privacyidea pull request #2786
Opened 2021-06-18 10:34 UTC by cornelinux

If the tokeninfo "last_auth" contains faulty datestring,
an exception is raised.
This is bad for the token-janitor and also for automatic tasks.

So we catch this exception and return False.

Closes #2780

2021-06-24 10:06 UTC, plettich approved these changes
Looks good, but we have to keep in mind that if we allow to negate a search, this would break...

2021-06-24 10:12 UTC, plettich requested changes
I was just thinking, maybe we should keep the error and catch it in the calling function. Just to avoid a wrong assumption: either the last_auth is "newer", "older" or it could not be read.

2021-06-24 12:51 UTC, cornelinux commented
> I was just thinking, maybe we should keep the error and catch it in the calling function. Just to avoid a wrong assumption: either the last_auth is "newer", "older" or it could not be read.

My logic thinking was:

"find all tokens, that are older than the given date"...

A token, that has no given date will not be older, so it would not be in the list. But catching the exception here, avoids breaking a loop.

and 

"find all tokens, that are newer than the given date"...

Also in this case a token with a invalid date would again not be part of this list.

I also was thinking back and forth were to put this, and with the argument that a token with an invalid date is neither older nor newer I ended up with this. But I am still open for discussion.

2021-07-07 09:46 UTC, plettich requested changes

2021-07-07 09:47 UTC, plettich commented
> I also was thinking back and forth were to put this, and with the argument that a token with an invalid date is neither older nor newer I ended up with this. But I am still open for discussion.

I think we can work with this for now but we should keep that in mind.

2021-07-07 11:45 UTC, cornelinux commented on privacyidea/lib/tokenclass.py
> +        It returns False, if the data in the token can not be parsed
Done in 07cfb461

2021-07-07 14:45 UTC, plettich approved these changes

2021-07-07 14:45 UTC, merged