Add a safe_store feature for token attributes
privacyidea/privacyidea pull request #2795
Opened 2021-06-24 07:33 UTC by cornelinux

tokeninfos and tokenowner information can fail to
be saved (or fail to return the DB id) in certain
database scenarios. This adds the possibility for a safe store
by reading the ID in a new request.

Closes #2794

2021-07-05 15:00 UTC, plettich requested changes
Looks good so far.
In the future we should make use of the generic `MethodsMixin` and the provided `safe`/`delete` functions more often.

2021-07-06 13:03 UTC, cornelinux commented
> Looks good so far.
> In the future we should make use of the generic `MethodsMixin` and the provided `safe`/`delete` functions more often.

I think in many cases the save functions are currently rather specific with some logical checks so these can currently not be mixed in. But I am always in for using less lines of code! :-)

2021-07-06 13:05 UTC, cornelinux commented on doc/installation/system/inifile.rst
> +database object in an additional request and not return it directly.
Sounds sensible. Will do. Maybe "SELECT"...

2021-07-06 13:05 UTC, cornelinux commented on doc/installation/system/inifile.rst
> +   row is otherwise not present". In this case setting ``PI_DB_SAFE_STORE`  to *True*
Will do.

2021-07-06 13:08 UTC, pep8speaks commented
Hello @cornelinux! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`privacyidea/models.py`](https://github.com/privacyidea/privacyidea/blob/0cada8d6cf96fe8227801f4372bb9767b687ddbb/privacyidea/models.py):

> [Line 3059:9](https://github.com/privacyidea/privacyidea/blob/0cada8d6cf96fe8227801f4372bb9767b687ddbb/privacyidea/models.py#L3059): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 3060:1](https://github.com/privacyidea/privacyidea/blob/0cada8d6cf96fe8227801f4372bb9767b687ddbb/privacyidea/models.py#L3060): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2021-07-06 13:08 UTC, cornelinux commented on doc/installation/system/inifile.rst
> +database object in an additional request and not return it directly.
Done in 0cada8d6

2021-07-06 13:08 UTC, cornelinux commented on doc/installation/system/inifile.rst
> +   row is otherwise not present". In this case setting ``PI_DB_SAFE_STORE`  to *True*
Done in 0cada8d6

2021-07-06 13:08 UTC, cornelinux commented on doc/installation/system/inifile.rst
> +database object in an additional request and not return it directly.
I also added some more text. I hope you will like it :-)

2021-07-07 09:51 UTC, plettich approved these changes
looks good

2021-07-07 09:51 UTC, merged