let token handler act on all tokens (at token_load)
privacyidea/privacyidea pull request #2833
Opened 2021-07-20 12:22 UTC by laclaro

The serials, which are processed by token_load were already present in the token event handler in the audit object.

This PR uses this data to act on all tokens which were loaded on import_token.

2021-07-20 12:22 UTC, pep8speaks commented
Hello @laclaro! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`privacyidea/lib/eventhandler/tokenhandler.py`](https://github.com/privacyidea/privacyidea/blob/5230f7874f1497510958d1174f42ecd1722e078a/privacyidea/lib/eventhandler/tokenhandler.py):

> [Line 403:30](https://github.com/privacyidea/privacyidea/blob/5230f7874f1497510958d1174f42ecd1722e078a/privacyidea/lib/eventhandler/tokenhandler.py#L403): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 403:30](https://github.com/privacyidea/privacyidea/blob/5230f7874f1497510958d1174f42ecd1722e078a/privacyidea/lib/eventhandler/tokenhandler.py#L403): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 404:30](https://github.com/privacyidea/privacyidea/blob/5230f7874f1497510958d1174f42ecd1722e078a/privacyidea/lib/eventhandler/tokenhandler.py#L404): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four

2021-07-20 19:11 UTC, cornelinux requested changes
Can you please add a testcase - maybe with a token eventhandler that disables loaded tokens?
You can create a dummy import file and eheck afterwards if all loaded tokens exist and are disabled.

Also I am not sure, if the list of the tokens is truncated at this point (or we may be before the DB write, so we could have a striing with all 1000 imported tokens)
Problem: The string in `g.audit_object.audit_data.get("serial")` could get very long and I am not sure, if it is truncated at a certain point.

2021-07-21 10:17 UTC, pep8speaks commented
Hello @laclaro! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`tests/test_api_token.py`](https://github.com/privacyidea/privacyidea/blob/55c635a85108c216968add6cb4e246f02dfcd52f/tests/test_api_token.py):

> [Line 1117:21](https://github.com/privacyidea/privacyidea/blob/55c635a85108c216968add6cb4e246f02dfcd52f/tests/test_api_token.py#L1117): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '['
> [Line 1117:96](https://github.com/privacyidea/privacyidea/blob/55c635a85108c216968add6cb4e246f02dfcd52f/tests/test_api_token.py#L1117): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ']'

2021-07-21 10:19 UTC, laclaro commented
I implemented a test for 100 imported tokens. I tested also with 1000 (which takes long!) and it also works.

2021-07-22 16:52 UTC, cornelinux approved these changes

2021-07-22 18:00 UTC, cornelinux commented
In `check_serial_valid` we actually check the serial number, which is not allowed to contain a comma.

So my change would allow a list of serials like

    serial1, serial2, serial3

but also

     serial1,serial2, serial3      ,    serial4

2021-07-22 18:12 UTC, merged