custom user attribute handler docu
privacyidea/privacyidea pull request #3101
Opened 2022-04-19 10:20 UTC by jona-samuel

This is the first version of the docu for the custom user attribute event handler. Feedback is very welcome.

2022-04-23 07:44 UTC, cornelinux commented
@jona-samuel Please rebase this PR on the `branch-3.7`. Get in touch if unclear how to do this locally.

2022-04-23 08:03 UTC, cornelinux requested changes
Hi @jona-samuel 
Please see my suggestions.

Also ensure:

* ~~set the link to this documentation in the index.rst~~
* rebase to 3.7
* ~~check if tags are allowed or not.~~

2022-04-23 08:03 UTC, cornelinux commented on doc/eventhandler/customuserattributehandler.rst
> +
My Suggestion:

---
This action deletes a custom user attribute on a certain event.

The action takes the options `attrkey` and `user` as described above.

For example you could set a custom user attribute on the token enrollment process, that indicates, that this is a new user and set a custom user attribute to "new user maybe needs help by the first login".
On the first successful login this custom user attribute could be automatically deleted using this event handler.

2022-04-26 11:52 UTC, jona-samuel commented on doc/eventhandler/customuserattributehandler.rst
> +"this user has log-in problems".
this is correct

2022-04-26 15:15 UTC, cornelinux requested changes
Thanks a lot.
This is better readable. However, my last request is, that you format certain words (e.g. with backticks), that indicate as key words, this also helps to logically understand the text better.

2022-04-26 15:15 UTC, cornelinux commented on doc/eventhandler/customuserattributehandler.rst
> +The action takes the options attrkey, attrvalue and user.
Please mark the names of the options "attrkey" and "attrvalue", this way it is easier to read.

You can do this with the backticks "`" before and after the word.

Also check for this in the remaining text.

2022-04-28 08:28 UTC, closed without merging

2022-04-28 08:28 UTC, jona-samuel commented
Replaced with new PR