Compare user based on uid
privacyidea/privacyidea pull request #3189
Opened 2022-06-16 11:26 UTC by cornelinux

Fixes #3186

2022-06-16 14:25 UTC, pep8speaks commented
Hello @cornelinux! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`tests/test_lib_user.py`](https://github.com/privacyidea/privacyidea/blob/ae2e52457a136d5ece69cddbaceb61249ffad6f0/tests/test_lib_user.py):

> [Line 507:51](https://github.com/privacyidea/privacyidea/blob/ae2e52457a136d5ece69cddbaceb61249ffad6f0/tests/test_lib_user.py#L507): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is None:'

2022-06-20 14:51 UTC, cornelinux commented
> Hello @cornelinux! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:
> 
> * In the file [`tests/test_lib_user.py`](https://github.com/privacyidea/privacyidea/blob/ae2e52457a136d5ece69cddbaceb61249ffad6f0/tests/test_lib_user.py):
> 
> > [Line 507:51](https://github.com/privacyidea/privacyidea/blob/ae2e52457a136d5ece69cddbaceb61249ffad6f0/tests/test_lib_user.py#L507): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is None:'

I am doing `== None`  on purpose, to actually test the `__eq__` method.

2022-06-22 13:31 UTC, plettich requested changes

2022-06-22 14:03 UTC, cornelinux commented on tests/test_lib_user.py
> +        self.assertFalse(User("root", self.realm1) == User("salesmann", "ldap"))
thx. done in ceca6a97

2022-06-22 14:04 UTC, cornelinux commented on privacyidea/lib/user.py
> +        log.info(u"Comparing based on login: {0!s} vs {1!s}".format(self.login, other.login))
OK, will downgrade this to debug.

2022-06-22 14:06 UTC, cornelinux commented on privacyidea/lib/user.py
> +        log.info(u"Comparing based on login: {0!s} vs {1!s}".format(self.login, other.login))
Done in eb225a8f

2022-06-23 12:28 UTC, plettich approved these changes

2022-06-23 12:28 UTC, merged