3352/fire base remove requirement of app parameters
privacyidea/privacyidea pull request #3397
Opened 2022-12-06 12:41 UTC by jona-samuel

Remove unnecessary FireBase parameters

2022-12-07 08:06 UTC, cornelinux requested changes
Looks good so far. I have two minor comments:

1. Please change the json loading.
2. Also add documentation or update docs

See here: https://github.com/privacyidea/privacyidea/blob/064328eca4c61c5fe03a928df97d2352d2f7da0d/doc/configuration/sms_gateway_config.rst#L21

2022-12-08 10:05 UTC, jona-samuel commented on privacyidea/lib/smsprovider/FirebaseProvider.py
> +            server_config = json.load(f)
json.loads can load files

2022-12-08 12:52 UTC, cornelinux commented on privacyidea/lib/smsprovider/FirebaseProvider.py
> +            server_config = json.load(f)
thanks!

2022-12-08 12:56 UTC, cornelinux approved these changes

2022-12-08 12:56 UTC, merged