Remove unicode/("u")
privacyidea/privacyidea pull request #3474
Opened 2023-01-20 10:53 UTC by jona-samuel

2023-01-24 16:01 UTC, NNLemling commented on privacyidea/lib/token.py
> +               'desc': _("Admin is allowed to initalize {0!s} tokens.").format(ttype.upper()),
While we're at it, please fix the spelling mistake

2023-01-24 16:14 UTC, NNLemling commented
Please check the following files:

privacyidea/tools/privacyidea-create-sqlidresolver-user         **line:45:**       
privacyidea/tools/privacyidea-create-pwidresolver-user         **line:45:**

2023-01-24 16:16 UTC, NNLemling requested changes
Please check the following files:

privacyidea/tools/privacyidea-create-sqlidresolver-user line:45:
privacyidea/tools/privacyidea-create-pwidresolver-user line:45:

2023-01-26 09:53 UTC, jona-samuel commented on privacyidea/lib/token.py
> +               'desc': _("Admin is allowed to initalize {0!s} tokens.").format(ttype.upper()),
https://github.com/privacyidea/privacyidea/pull/3474/commits/3e03fb02c7ae87ee14200346b20c52b9e250155b

2023-01-26 12:53 UTC, NNLemling approved these changes

2023-01-26 12:53 UTC, merged