3438/catching error missing password in auth request
privacyidea/privacyidea pull request #3572
Opened 2023-03-20 11:46 UTC by jona-samuel

2023-03-20 19:37 UTC, cornelinux approved these changes

2023-03-20 19:38 UTC, cornelinux requested changes
@jona-samuel  Please check for the failing tests in test_api_auth!

2023-03-27 16:11 UTC, plettich requested changes
Maybe we should just check if the password variable is set:
```
if password:
    ....
```
that way we don't have to change all the tests.
Also the error message "Authentication failure. Wrong credentials" might be more appropriate to avoid disclosing information.
We could add a debug/info log entry to inform in the logs that the parameter is missing.

2023-04-04 10:49 UTC, closed without merging

2023-04-04 10:49 UTC, jona-samuel commented
replaced buy https://github.com/privacyidea/privacyidea/pull/3586