3578/Threat ID for POST requests
privacyidea/privacyidea pull request #3636
Opened 2023-05-23 13:17 UTC by NNLemling

The matching code from the following functions:

https://github.com/privacyidea/privacyidea/blob/bffc54f23d1444706bbb343101b283127954be6e/privacyidea/api/before_after.py#L150
https://github.com/privacyidea/privacyidea/blob/bffc54f23d1444706bbb343101b283127954be6e/privacyidea/api/auth.py#L88
https://github.com/privacyidea/privacyidea/blob/bffc54f23d1444706bbb343101b283127954be6e/privacyidea/api/validate.py#L125
https://github.com/privacyidea/privacyidea/blob/bffc54f23d1444706bbb343101b283127954be6e/privacyidea/api/ttype.py#L57

Has been combined into:

https://github.com/privacyidea/privacyidea/blob/0a9c618e6e6c6c8a43cb33df490cf45a802b2cbd/privacyidea/api/before_after.py#L87

In addition, the threatid is now also stored in the audit log for POST requests.

closes #3578

2023-05-23 14:29 UTC, plettich requested changes

2023-05-23 14:29 UTC, plettich commented on privacyidea/api/before_after.py
> +    g.client_ip = get_client_ip(request,
we should add the headers here as well, even if they weren't used in the `ttype` endpoint.

2023-05-23 14:29 UTC, plettich commented on privacyidea/api/validate.py
> +import threading
this isn't needed here anymore. Please also remove all the unused imports as well.

2023-05-24 13:30 UTC, NNLemling commented on privacyidea/api/ttype.py
> -    ensure_no_config_object()
fixed in 62b62c31021068d312615ebaaa0919793f0afd60

2023-05-26 11:22 UTC, closed without merging