3599/Declined push requests
privacyidea/privacyidea pull request #3644
Opened 2023-06-01 08:27 UTC by jona-samuel

Adding the declined info to the validate return and the audit log

2023-06-01 12:19 UTC, cornelinux commented on privacyidea/api/validate.py
> +        "info": "transaction_id: {}, status: {}".format(transaction_id, details.get("challenge_status")),
I suggest puttig the transation id in `action_detail` and the status in `info`.

2023-06-07 10:26 UTC, NNLemling commented
I sometimes get a syntax error message.

```
privacyidea/lib/utils/__init__.py:1283: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif not obj and (details.get("challenge_status") is "declined"):
```

This error message appears from python version 3.8 onwards. Maybe you check again if "==" fits better here.

2023-06-07 10:28 UTC, NNLemling requested changes

2023-06-09 21:24 UTC, cornelinux commented on privacyidea/lib/utils/__init__.py
> +        elif not obj and (details.get("challenge_status") is "declined"):
using "==" is actually correct. "is" compares to a singleton.

2023-06-09 21:33 UTC, cornelinux requested changes

2023-06-09 21:33 UTC, cornelinux commented on privacyidea/api/validate.py
> +    decline_challenges = []
Please name this "declined_challenges", since it contains the challenges, that have been declined.

2023-06-09 21:33 UTC, cornelinux commented on privacyidea/api/validate.py
> +        details = {"challenge_declined": "accept"}
I think this has to be

~~~~
details = {"challenge_status": "accept"}
~~~~

challenge_declined -> challenge_status

2023-06-09 21:33 UTC, cornelinux commented on privacyidea/lib/tokens/pushtoken.py
> +                            chal.set_data("challenge_declined")
When will the challenge be removed?

2023-06-09 21:40 UTC, cornelinux commented on privacyidea/lib/utils/__init__.py
> +        elif not obj and (details.get("challenge_status") is "declined"):
Done

2023-06-09 21:44 UTC, cornelinux approved these changes

2023-06-09 21:52 UTC, merged