Add userinformation to tokenrollout
privacyidea/privacyidea pull request #3690
Opened 2023-07-15 06:36 UTC by cornelinux

Pre-Populating the email address and the mobile number with data from the user store, if a user enrolls such a token.

Closes #3688

2023-07-19 14:56 UTC, plettich requested changes

2023-07-20 12:16 UTC, cornelinux commented on privacyidea/static/components/token/controllers/tokenControllers.js
> +        UserFactory.getUserDetails({}, function(data) {
Will do. I will add `checkRight()`.

2023-07-20 13:12 UTC, cornelinux commented on privacyidea/static/components/token/controllers/tokenControllers.js
> +        UserFactory.getUserDetails({}, function(data) {
Done in b88e58da

2023-07-24 09:32 UTC, cornelinux commented
@plettich Do you want to take a look at it? I added `checkRight`  and tested it. Otherwise I will merge it tomorrow.

2023-07-24 12:16 UTC, plettich approved these changes

2023-07-24 12:16 UTC, merged