added token description in user notification event handler
privacyidea/privacyidea pull request #3767
Opened 2023-09-25 08:02 UTC by maxstaubach

2023-09-28 11:26 UTC, jona-samuel requested changes

2023-09-28 11:26 UTC, jona-samuel commented on privacyidea/lib/eventhandler/usernotification.py
> +                    tokendescription = tokens[0].token.description
can you please read a test for this

2023-10-09 09:59 UTC, cornelinux commented
@jona-samuel Please add the test yourself and assign me for review again.

2023-10-16 09:06 UTC, jona-samuel commented
Replaced by https://github.com/privacyidea/privacyidea/pull/3783

2023-10-16 09:06 UTC, closed without merging