Add the possibility to write info to audit log
privacyidea/privacyidea pull request #3782
Opened 2023-10-11 12:48 UTC by cornelinux

An event handler can now write additional info to the audit log.

Closes #3781

2023-10-20 08:26 UTC, jona-samuel requested changes
Is it possible to test this?
If there isn't a good way to test this, then it can get merged

2023-10-22 08:07 UTC, cornelinux commented
I investigated the scenarios on a live example.

Since it also is not clear, what the smtplib returns in case of

a) a wrong server name (IP not exist)
b) a mailbox does not exist locally (after connect)

I will check to use `smtpmock`.

2023-10-25 15:10 UTC, pep8speaks commented
Hello @cornelinux! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`tests/test_api_events.py`](https://github.com/privacyidea/privacyidea/blob/56e7627b1db07c7c52d4d4a975259505fdd97bad/tests/test_api_events.py):

> [Line 769:1](https://github.com/privacyidea/privacyidea/blob/56e7627b1db07c7c52d4d4a975259505fdd97bad/tests/test_api_events.py#L769): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2023-10-27 08:19 UTC, jona-samuel requested changes
Looks good, but please fix the typo

2023-10-29 05:33 UTC, cornelinux commented
@jona-samuel I fixed the typo and also added a further test for pre-event-handling.
The code cov should be fine, now.

2023-10-29 07:00 UTC, cornelinux commented on tests/test_lib_eventhandler_usernotification.py
> +        audit_object.audit_data["serial"] = "123456"
Fixed in 5cf0c430a5cd37b64b37fb010aeeaa8858574a95

2023-10-30 09:14 UTC, jona-samuel approved these changes

2023-10-30 09:14 UTC, merged