Mark privacyidea token in the qr code
privacyidea/privacyidea pull request #3909
Opened 2024-04-17 08:25 UTC by jona-samuel

closes #3902 

Is 'creator' fine as the new tag?

![frame](https://github.com/privacyidea/privacyidea/assets/63372780/b111841a-c55c-47f9-956a-e4451d1763d2)

The QR code locks lick this new. Please check that all apps work with it.

2024-04-17 10:12 UTC, frankmer commented
privacyIDEA Authenticator can handle hotp or totp in upper case. To work with any common authenticator it has to be lowercase.
The authenticators I used just ignore the creator parameter and can scan the QR if I set the token type to lower case.

I will implement our app to use the creator parameter.

2024-04-17 10:32 UTC, frankmer requested changes

2024-04-17 10:32 UTC, frankmer commented on tests/test_lib_apps.py
>          self.assertTrue("otpauth://TOTP/mylabel?secret=CI2FM&period"
totp must be lowercase

2024-04-24 09:00 UTC, jona-samuel commented on tests/test_lib_apps.py
> +        r = create_google_authenticator_url(tokentype="totp", key="123456",
[14084c2](https://github.com/privacyidea/privacyidea/pull/3909/commits/14084c252925b2247c5a4415a41506c4837c404a)

2024-04-24 09:00 UTC, jona-samuel commented on privacyidea/lib/apps.py
> +            "creator=privacyidea&"
[14084c2](https://github.com/privacyidea/privacyidea/pull/3909/commits/14084c252925b2247c5a4415a41506c4837c404a)

2024-04-25 12:41 UTC, plettich requested changes

2024-04-25 12:41 UTC, plettich commented on privacyidea/lib/apps.py
> +        tokentype = "totp"
I meant something like
`tokentype = tokentype.lower()`
at the beginning of the function. So what ever is passed to the function as a tokentype is converted to lower case.

2024-04-30 10:31 UTC, plettich approved these changes

2024-04-30 10:31 UTC, merged