Check Yubikey OTP length before validating
privacyidea/privacyidea pull request #3929
Opened 2024-05-06 10:31 UTC by jona-samuel

closes #3746

2024-05-08 08:43 UTC, jona-samuel commented
should we implement this for totp, hotp, SMS and email too?

2024-05-08 12:11 UTC, pep8speaks commented
Hello @jona-samuel! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`privacyidea/lib/decorators.py`](https://github.com/privacyidea/privacyidea/blob/d4d01377a7de75198c82269053699bec22f4b43c/privacyidea/lib/decorators.py):

> [Line 48:1](https://github.com/privacyidea/privacyidea/blob/d4d01377a7de75198c82269053699bec22f4b43c/privacyidea/lib/decorators.py#L48): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1





















* In the file [`tests/test_lib_tokens_yubikey.py`](https://github.com/privacyidea/privacyidea/blob/d4d01377a7de75198c82269053699bec22f4b43c/tests/test_lib_tokens_yubikey.py):

> [Line 260:5](https://github.com/privacyidea/privacyidea/blob/d4d01377a7de75198c82269053699bec22f4b43c/tests/test_lib_tokens_yubikey.py#L260): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2024-05-13 09:20 UTC, plettich requested changes

2024-05-13 09:20 UTC, plettich commented on privacyidea/lib/decorators.py
> +def check_token_otp_lenght(func):
please correct to `check_token_otp_length()`

2024-05-13 09:20 UTC, plettich commented on privacyidea/lib/tokens/emailtoken.py
> +    @check_token_otp_lenght
please move this decorator one line up. Decorators are applied from bottom to top (innermost first). We should first check if the token is locked and then if the otp length matches.

2024-05-13 09:20 UTC, plettich commented on privacyidea/lib/tokens/hotptoken.py
> +    @check_token_otp_lenght
see above

2024-05-13 09:20 UTC, plettich commented on privacyidea/lib/tokens/smstoken.py
> +    @check_token_otp_lenght
and all others...

2024-05-13 09:20 UTC, plettich commented on privacyidea/lib/tokens/yubikeytoken.py
> +            log.debug("OTP could not be decode")
please change to `could not be decoded`

2024-06-03 10:07 UTC, plettich approved these changes

2024-06-03 10:07 UTC, merged