Change AUTHTYPE.SASL_KERBEROS behaviour if upn ist present in userinfo values for multidomain support
privacyidea/privacyidea pull request #3987
Opened 2024-06-25 13:21 UTC by topelrapha

We use privacyIdea with multiple ldap resolvers, want to use Kerberos authentication and had the problem that just one domain the default domain works fine. All users not being part of default domain got an error - and in log file it seems they were matched to default domain.

This fix shouldn't break the default behaviour but works with multiple ldap resolvers / multiple domains and kerberos authentication if following the next steps:

- Required Kerberos configuration incl. keytab files on Linux machine
- ADD "upn" : "userPrincipalName" (works if ldap is ActiveDirectory) to attribute values in ldap resolver configuration
- Switch bind type to "SASL Kerberos"

The fix takes care if there is a value in upn, modify this value to uppercase and use the result instead of just the username (without realm).

2024-06-25 13:21 UTC, pep8speaks commented
Hello @topelrapha! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`privacyidea/lib/resolvers/LDAPIdResolver.py`](https://github.com/privacyidea/privacyidea/blob/80ed39b1d4bc3e7a7aa2bd760727f57b071b9129/privacyidea/lib/resolvers/LDAPIdResolver.py):

> [Line 349:49](https://github.com/privacyidea/privacyidea/blob/80ed39b1d4bc3e7a7aa2bd760727f57b071b9129/privacyidea/lib/resolvers/LDAPIdResolver.py#L349): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 349:107](https://github.com/privacyidea/privacyidea/blob/80ed39b1d4bc3e7a7aa2bd760727f57b071b9129/privacyidea/lib/resolvers/LDAPIdResolver.py#L349): [E271](https://duckduckgo.com/?q=pep8%20E271) multiple spaces after keyword
> [Line 349:121](https://github.com/privacyidea/privacyidea/blob/80ed39b1d4bc3e7a7aa2bd760727f57b071b9129/privacyidea/lib/resolvers/LDAPIdResolver.py#L349): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (147 > 120 characters)

2024-07-12 10:03 UTC, nilsbehlen requested changes

2024-07-12 10:03 UTC, nilsbehlen commented on privacyidea/lib/resolvers/LDAPIdResolver.py
> +#             Change AUTHTYPE.SASL_KERBEROS behaviour if upn ist present in userinfo values for multidomain support
`ist` should be `is`

2024-07-12 10:03 UTC, nilsbehlen commented on privacyidea/lib/resolvers/LDAPIdResolver.py
> +            if self.getUserInfo(uid).get('upn') is not None \
please assign `self.getUserInfo(uid).get('upn')` to a variable, so it is only done once and improves readability

2024-07-12 11:18 UTC, plettich commented
The Problem with this PR is, that it uses a user defined name for the UPN.
I think it is a good idea to generally add the UPN to the attribute list for an ldap resolver (if it is available) since it is more precise than just the `sAMAccountName`. Than we can use this attribute anywhere.

2024-07-12 11:45 UTC, nilsbehlen commented
We should probably add the upn to the standard mapping of the ldapresolver.

2024-10-21 11:00 UTC, nilsbehlen approved these changes

2024-10-21 11:00 UTC, merged