4026 declining a push challenge has no effect
privacyidea/privacyidea pull request #4027
Opened 2024-08-01 08:46 UTC by frankmer

Polling after declining a challenge:

App-log before:
![image](https://github.com/user-attachments/assets/90587a75-7c2b-4799-b66c-7137ca828997)
![image](https://github.com/user-attachments/assets/280a3a9c-e036-4760-9ff5-95b7f84639fc)
![image](https://github.com/user-attachments/assets/eae2d5d2-864f-4894-8c71-fde921d6a16d)

App-log after:
![image](https://github.com/user-attachments/assets/f7dd35b8-6a33-4989-ab0a-348613bb6c8d)
![image](https://github.com/user-attachments/assets/905981ce-bff0-4488-bf68-a0ec3b745f4f)

2024-08-01 14:08 UTC, plettich requested changes

2024-08-02 12:49 UTC, nilsbehlen commented on tests/test_api_ttype.py
> +        # If the challenge is successfully declined, the /validate/check endpoint
the /ttype/push endpoint, used for polling,

2024-08-05 08:10 UTC, nilsbehlen approved these changes

2024-08-05 11:33 UTC, plettich approved these changes

2024-08-05 11:33 UTC, merged