Description required when editing with the corresponding active policy
privacyidea/privacyidea pull request #4117
Opened 2024-10-24 09:16 UTC by henrik-falk

for each type individually.

2025-07-03 08:54 UTC, plettich requested changes

2025-07-03 08:54 UTC, plettich commented on doc/policies/managment.rst
> +~~~~~~~~~~~~~~~~~~~~
Please extend the `~` line to the length of the text above, otherwise sphinx complains.

2025-07-03 08:54 UTC, plettich commented on privacyidea/api/lib/prepolicy.py
> +            log.warning(_("Missing description for {} token.".format(type_value)))
We don't need to translate warnings, they just end up in the log. Also I *think* we always log it as an `ERROR` message when raising an error.

2025-07-03 09:53 UTC, nilsbehlen commented on privacyidea/api/lib/prepolicy.py
> +        serial = getParam(params, "serial")
`get_required` or `get_optional` instead of `getParam`

2025-07-03 09:56 UTC, nilsbehlen commented on privacyidea/api/lib/prepolicy.py
> +        description = request.all_data.get("description", "").strip()
indent this and the following lines one more and remove `tok=None`

2025-07-03 09:56 UTC, nilsbehlen commented on privacyidea/api/lib/prepolicy.py
> +    if type_value in token_types:
or check serial here, without serial this can not work anyway?

2025-07-03 09:57 UTC, nilsbehlen commented on privacyidea/lib/policy.py
> +
remove emtpy line

2025-07-07 10:39 UTC, jona-samuel commented on doc/policies/managment.rst
> +The scope *management* defines what happens when managing tokens
Is this just for tokens or also containers?

2025-07-07 10:43 UTC, jona-samuel commented on privacyidea/api/lib/prepolicy.py
> +            log.error(("Missing description for {} token.").format(type_value))
We should use the opportunity to change this in an f-string

2025-07-07 10:47 UTC, jona-samuel commented on privacyidea/api/lib/prepolicy.py
> +            log.error(("Missing description for {} token.".format(type_value)))
f-string

2025-07-07 10:52 UTC, jona-samuel commented on privacyidea/api/token.py
> +from privacyidea.api.lib.prepolicy import require_description
Is there a reason for a separate import?

2025-07-07 13:59 UTC, jelinaunger commented on doc/policies/managment.rst
> +.. _management_policies:
Typo in the filename: manag**e**ment.rst

You need to add this file to the toctree in index.rst.

2025-07-07 14:07 UTC, jelinaunger commented on privacyidea/api/token.py
> +    request.all_data["type"] = tokenobject_list[0].type
What if the token can not be found due to an invalid serial or wrong user?
Maybe use the function `get_one_token(serial=serial)` which raises a ResourceNotFoundError if the token does not exist.

2025-07-07 14:08 UTC, jelinaunger commented on privacyidea/api/token.py
> +    tokenobject_list = get_tokens_from_serial_or_user(serial=serial, user=user)
I would prefer "tokens"

2025-07-07 14:58 UTC, nilsbehlen commented on privacyidea/api/token.py
> +    token = get_one_token(serial=serial)
we have the token object here. passing the serial to set_description, which will get the token again is inefficient. so it would be good to have set_description take a token object as input.
Add it as an optional parameter and if both serial and token object would be set, use the token object.

2025-07-17 10:58 UTC, nilsbehlen approved these changes

2025-07-17 10:59 UTC, merged