fix require presence for multiple challenges
privacyidea/privacyidea pull request #4129
Opened 2024-10-28 14:31 UTC by nilsbehlen

2024-10-28 14:36 UTC, nilsbehlen commented
sorry lots of formatting

2024-11-05 13:14 UTC, plettich requested changes
Just the `nonce` issue... if it isn't required anymore, we should explain that.

2024-11-05 13:22 UTC, nilsbehlen commented on privacyidea/lib/tokens/pushtoken.py
> +                    sign_data = f"{challenge.challenge}|{serial}"
the nonce is pointless as a parameter in the request. the server should not use parameters given by a client to verify something (other than the signature, and in this case). the server uses the parameters from its database to check the signature and if the signature does not match, we raise an error. i do not think we should to tell the client that the nonce it used was wrong by comparing the one from the db with the one from the request.

2024-11-05 13:23 UTC, nilsbehlen commented
i have a note hanging on my screen to update the doc with the changes/removal of the nonce parameter, i only need to do it

2024-11-05 13:55 UTC, frankmer approved these changes

2024-11-05 15:09 UTC, nilsbehlen commented
i have only found the doc inside the pushtoken class. since the push response is handled over the generic `/ttype/` endpoint, there is no doc for that endpoint. i also adjusted the concept in the wiki.

2024-11-05 15:33 UTC, pep8speaks commented
Hello @nilsbehlen! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`privacyidea/lib/tokens/pushtoken.py`](https://github.com/privacyidea/privacyidea/blob/17d37d29b043e17c091d8da7e18e0c7421de52ac/privacyidea/lib/tokens/pushtoken.py):

> [Line 687:46](https://github.com/privacyidea/privacyidea/blob/17d37d29b043e17c091d8da7e18e0c7421de52ac/privacyidea/lib/tokens/pushtoken.py#L687): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'

2024-11-05 17:24 UTC, plettich commented on privacyidea/lib/tokens/pushtoken.py
> +                    sign_data = f"{challenge.challenge}|{serial}"
So basically we send the challenge data as the nonce :-) It is just not described like that everywhere.

2024-11-05 20:14 UTC, plettich requested changes

2024-11-05 20:14 UTC, plettich commented on privacyidea/lib/tokens/pushtoken.py
>                signature=<signature over {nonce}|{serial}|decline
like above

2024-11-06 07:25 UTC, nilsbehlen commented on privacyidea/lib/tokens/pushtoken.py
>                signature=<signature over {nonce}|{serial}>
like i said, we do not need that parameter any more, i so have removed it

2024-11-11 08:54 UTC, merged