fix two references in documentation
privacyidea/privacyidea pull request #4140
Opened 2024-11-11 11:35 UTC by samir-at-netknights

In [the current documentation](https://privacyidea.readthedocs.io/en/v3.10/overview/index.html), two references do not resolve. This commit sets it to the correct references:
- https://github.com/privacyidea/privacyidea/blob/master/doc/installation/system/pi-manage.rst?plain=1#L1
- https://github.com/privacyidea/privacyidea/blob/master/doc/eventhandler/index.rst?plain=1#L1

Marking it as a draft since I can't get the current master to build the documentation and test it.

2024-11-14 18:21 UTC, plettich requested changes
We have some information about building the documentation locally here:
https://github.com/privacyidea/privacyidea/blob/15a9422b0695b40e61797c0f1965285a4441aa19/CONTRIBUTING.md?plain=1#L66
After the build is finished, just point Your browser to `doc/_build/html/index.html`

2024-11-14 18:21 UTC, plettich commented on doc/overview/index.rst
> +  You can use again :ref:`policies` and :ref:`eventhandler`s to implement these.
please remove the trailing `s` after `eventhandler`, it breaks the link.

2024-11-14 18:21 UTC, plettich commented on doc/overview/index.rst
> +  also need to take a closer look at the :ref:`pimanage`.
please remove the `the` since the generated link text already contains a `the`.

2024-11-15 15:23 UTC, samir-at-netknights commented
Applied your requested changes.
I did try the steps listed in the CONTRIBUTING file before creating this PR. I just retried with a fresh virtualenv and then even in a fresh Ubuntu 24.04 VM. Same result:
[make_html.txt](https://github.com/user-attachments/files/17777517/make_html.txt)

2024-11-15 15:28 UTC, samir-at-netknights commented
Update: The build works with `sphinxcontrib-plantuml==0.25` :thinking:.

2024-11-15 16:59 UTC, samir-at-netknights commented
It looks a bit strange but the references work now:
![image](https://github.com/user-attachments/assets/4b82f3b8-568f-4ab4-8a0a-d41d22f6fca2)

Is this fine?

2024-11-19 10:26 UTC, plettich requested changes
Looks good but can You rebase it onto `branch-3.10` so we'll have it fixed in the next bug-fix release?
I can confirm the error when building the documentation but this occurs only on the current master branch. I'll look into it.

2024-11-19 10:30 UTC, plettich commented
> Tested it on a working version of `sphinxcontrib-plantuml`. It looks a bit strange with the upper-case "The" but the references work now: 
> ...
> Is this fine?

We will need to go through the docs and check and fix some links someday but for now i think this is ok.
You can also change the text of the link: https://www.sphinx-doc.org/en/master/usage/referencing.html#role-ref

2024-11-19 10:50 UTC, samir-at-netknights commented
> Looks good but can You rebase it onto branch-3.10 so we'll have it fixed in the next bug-fix release?

Done!
> You can also change the text of the link: https://www.sphinx-doc.org/en/master/usage/referencing.html#role-ref

Thanks, it looks better now:
![grafik](https://github.com/user-attachments/assets/ff61c22c-7fcc-4f7e-ac00-5cea5599317d)

2024-11-19 15:51 UTC, merged