Fixing typo and update database
privacyidea/privacyidea pull request #4168
Opened 2024-11-29 13:01 UTC by jona-samuel

2024-11-29 13:01 UTC, pep8speaks commented
Hello @jona-samuel! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`migrations/versions/7301d5130c3a_.py`](https://github.com/privacyidea/privacyidea/blob/e031fe40b1c14b757e89b96953850626881692e8/migrations/versions/7301d5130c3a_.py):

> [Line 42:13](https://github.com/privacyidea/privacyidea/blob/e031fe40b1c14b757e89b96953850626881692e8/migrations/versions/7301d5130c3a_.py#L42): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented

2024-12-05 15:04 UTC, nilsbehlen requested changes
the correct spelling would be `urlencoded

2024-12-06 10:15 UTC, plettich requested changes

2024-12-06 10:15 UTC, plettich commented on migrations/versions/7301d5130c3a_.py
> +        for row in session.query(EventHandlerOption).filter(EventHandlerOption.Value == 'urlendcode'):
i think we should probably go with something like this:
```
op.execute("UPDATE eventhandleroption SET Value='urlencoded' WHERE Value='urlendcode'")
```
(See https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.execute)
I'll have to check if this works with all currently supported databases but this is regular SQL...

2024-12-06 10:15 UTC, plettich commented on migrations/versions/7301d5130c3a_.py
> +        for row in session.query(EventHandlerOption).filter(EventHandlerOption.Value == 'urlendcode'):
We could also use a rudimentary table definition or reflect it from the actual database and use SQLAlchemy constructs here.

2025-01-24 11:06 UTC, plettich commented
Works now with PostgreSQL, MySQL, Oracle, SQLite and Mariadb

2025-01-24 11:18 UTC, plettich approved these changes

2025-01-24 11:18 UTC, plettich approved these changes

2025-01-24 11:24 UTC, nilsbehlen approved these changes

2025-01-24 11:24 UTC, merged