policy documentation clean-up
privacyidea/privacyidea pull request #4178
Opened 2024-12-09 15:45 UTC by aleyna34131

This commit is the result of reading through the policy documentation and fixing mostly low-hanging fruits.
It also streamlines some things (like using versionadded where applicable), fixes formatting errors and compiler warnings, and using the new commands for pi-manage (this one I did for the entire documentation).
Two places where I also changed content were:
- in register.rst `requiredemail`, I fixed an example which seemed like it was wrongly copied from authentication.rst
- in enrollment.rst `max_active_token_per_user` I removed a sentence which seemed way out of place

Other than that, I don't think I changed anything relating to the content.

2024-12-10 12:27 UTC, aleyna34131 commented
> The changes are currently in `branch-3.10` but will be merged into master soon.

Can you please ping me once that happened? I'll just rebase then and notify you.

2024-12-10 13:25 UTC, plettich commented
> > The changes are currently in `branch-3.10` but will be merged into master soon.
> 
> Can you please ping me once that happened? I'll just rebase then and notify you.

Will do.

2025-01-13 11:57 UTC, nilsbehlen commented
ping

2025-01-13 15:34 UTC, aleyna34131 commented
@plettich rebased! :smile:

2025-01-15 19:02 UTC, plettich requested changes
Please have a look at my comments

2025-01-17 12:07 UTC, aleyna34131 commented on doc/policies/admin.rst
> +type: ``string``
What do you prefer? I just tried to make them all the same, I don't have a horse in this race :smile:.

2025-01-17 12:12 UTC, aleyna34131 commented on doc/policies/admin.rst
> +.. _admin_policies_hashlib:
I tried to fix a compiler warning, but this makes sense.
```
[..]/doc/policies/admin.rst:821: WARNING: duplicate label hotp-hashlib, other instance in [..]/doc/policies/user.rst
[..]/doc/policies/admin.rst:821: WARNING: duplicate label totp-hashlib, other instance in [..]/doc/policies/user.rst
[..]/doc/policies/user.rst:308: WARNING: duplicate label hotp-hashlib, other instance in [..]/doc/policies/admin.rst
[..]/doc/policies/user.rst:308: WARNING: duplicate label totp-hashlib, other instance in [..]/doc/policies/admin.rst
```
Would it make sense to change the links from the webui to unique anchors, or is this not a good idea?

2025-01-20 08:56 UTC, plettich commented on doc/policies/admin.rst
> +type: ``string``
i'd go with `integer`, `string` and `bool`. The recipients of the documentation might not be programmers :-)

2025-01-20 09:01 UTC, plettich commented on doc/policies/admin.rst
> +.. _admin_policies_hashlib:
Ah, we would need to change how we auto-generate the links to the documentation (currently like `.../policies/$(scope).html#$(policy-name)`). For now we need to live with the warnings.

2025-01-20 11:15 UTC, aleyna34131 commented on doc/policies/admin.rst
> +type: ``string``
Changed 'int' to 'integer' :+1:.

2025-01-20 11:17 UTC, aleyna34131 commented on doc/policies/admin.rst
> +.. _admin_policies_hashlib:
Left all anchors as they were now.

2025-01-20 11:18 UTC, aleyna34131 commented
@plettich applied your feedback, thanks!

2025-01-20 15:04 UTC, plettich approved these changes

2025-01-20 15:07 UTC, merged